### ISSUE TITLE
Release 2 Milestone Tasks

### ISSUE THREAD

**Issue by astralbodies** [wordpress-mobile/WordPressCom-Stats-iOS#207]
Listed in order of priority, these are the tasks that need to be completed for the 0.2.1 milestone.

## Must Get Done
- [x] Wonky published posts section #129
- [x] Add Search Terms section #154
- [x] Authors stats #117
- [x] Full screen view for list data #83
- [x] Track analytics on StatsViewAll and StatsSinglePostDetails #147

## Should Get Done
- [x] Helvetica showing through on Stats #221
- [x] Missing links on Tags & Categories #212
- [x] Web stats cell stays selected when tapped #210
- [x] Graph bar reselected after rotation which refetches #123

Remaining items not completed in this release moved to #230

**Comment by astralbodies** [comment]
Moved unfinished items over to Release 3 planning issue. Considering this milestone complete.
