### ISSUE TITLE
Release 3 Milestone Tasks

### ISSUE THREAD

**Issue by astralbodies** [wordpress-mobile/WordPressCom-Stats-iOS#230]
## Items not finished in Release 2
- [ ] Evaluate colors to match standards #217
- [ ] Add Country webview to match Android #209
- [ ] Action buttons for follow & spam #73
- [ ] Remove default Gravatar for search links if possible #206
- [ ] Rethink activity indicator for graph and overall #205
- [ ] Animate bar value changes #77
- [ ] Icons missing from Tag & Category entries #118

## If We Have Time (from Release 2)
- [ ] Published posts section should be collapsed upon loading #128
- [ ] Pagination is required on View All #178
- [ ] Add comment followers total to Comments section #155
- [ ] Navbar improvements #142
- [ ] Auto-fetch new data if time period has elapsed #111
- [ ] Advanced error handling & retry mechanisms #108
- [ ] Create separate data model for remote layer #94
- [ ] Extract helper methods into unit-testable classes #86
- [ ] Take NSLocale as parameter in services #80

## Un-prioritized new items for Release 3
- [ ] Add error condition display to post details and view all screens #224
- [ ] Enable all warnings (or close to all) in Xcode build #218
- [ ] Unify strings and pull from widgets.wp.com if possible #132

**Comment by astralbodies** [comment]
This is no longer valid to what's in Release 3. Will recreate.
