### ISSUE TITLE
Swift Conversation Master Issue

### ISSUE THREAD

**Issue by astralbodies** [wordpress-mobile/WordPressCom-Stats-iOS#404]
- [ ] Stats main view controller (with segmented control)
- [ ] Stats Table VC
- [ ] Insights
- [ ] Cells
- [ ] Graph VC
- [ ] Stats Service
- [ ] Stats Service Remote

Just spit-balling here but could be a fun side project and refactor.
