### ISSUE TITLE
Reinvent stats (all the things)

### ISSUE THREAD

**Issue by astralbodies** [wordpress-mobile/WordPressCom-Stats-iOS#60]
## Major changes
* Swift-ize the library in general
* Simplify the data models so they are human-readable and not buried in a generic collection
* Reimplement the UI using Storyboards where possible (ideally ALL of it)
* Reuse the UICollectionView-based bar graph.  Additional tweaks may be needed to genericize the data model behind it.
* Move to AlamoFire for networking calls.  Short term include it as a file until we figure out Modules.
* User Interface and Interaction designs are to come.  Prototype is currently internal to Automattic.

## Punch list
- [x] Links under heading should be indented to indicate hierarchy #14
- [x] Persist/Cache Stats downloaded data #15
- [x] Create Remote calls for Followers #65
- [x] Create remote calls for Comments #66
- [x] Add section for posts published within current period #67
- [x] When a bar is selected, highlight the entire section not just the bar #68
- [x] Display child items when they exist #70
- [x] Add a "more" selector if more than entries exist #71
- [x] Intelligently retry if remote call fails #72
- [x] Segmented control in a group #74
- [x] Show group totals when appropriate #75
- [x] Localize number formatting for counts and totals #76
- [x] Resolve date parameter issues for ranges #78
- [x] Improve subsection segmented control reload animation #81
- [x] No data result row should be more informative #85
- [x] Rows with URLs for post should launch in browser #114

## Deferred for next release
* Action buttons for follow & spam #73
* Animate bar value changes #77
* Full screen view for list data #83
* Extract helper methods into unit-testable classes #86
* Auto-fetch new data if time period has elapsed #111

## Towards the end
- [x] Design Review #69

**Comment by astralbodies** [comment]
This punch list is done. 0.2.0 will be v1 of Calypso stats.
